[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "api"
source = "apps/api"

[services.variables]
NODE_ENV = "production"
PORT = "3001"

[[services]]
name = "web"
source = "apps/web"

[services.variables]
NODE_ENV = "production"
PORT = "3000"